version: '3'
services:
    sciki:
        build:
            context: ./docker/
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        ports:
            - '${APP_PORT:-8888}:80'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - './src:/var/www/html'
        networks:
            - sciki
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './database/mysql:/var/lib/mysql'
        networks:
            - sciki
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        volumes:
            - './database/redis:/data'
        networks:
            - sciki
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        volumes:
            - './database/meilisearch:/data.ms'
        networks:
            - sciki
networks:
    sciki:
        driver: bridge
